// <auto-generated />
using AnimalShelterAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AnimalShelterAPI.Migrations
{
    [DbContext(typeof(AnimalShelterAPIContext))]
    [Migration("20210611164435_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.6");

            modelBuilder.Entity("AnimalShelterAPI.Models.Cat", b =>
                {
                    b.Property<int>("CatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Gender")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("CatId");

                    b.ToTable("Cats");

                    b.HasData(
                        new
                        {
                            CatId = 1,
                            Age = 4,
                            Description = "Lovely",
                            Gender = "Male",
                            Name = "Doug"
                        },
                        new
                        {
                            CatId = 2,
                            Age = 2,
                            Description = "Lovely",
                            Gender = "Male",
                            Name = "Bruce"
                        },
                        new
                        {
                            CatId = 3,
                            Age = 5,
                            Description = "Lovely",
                            Gender = "Male",
                            Name = "Steve"
                        },
                        new
                        {
                            CatId = 4,
                            Age = 9,
                            Description = "Lovely",
                            Gender = "Female",
                            Name = "Carla"
                        },
                        new
                        {
                            CatId = 5,
                            Age = 18,
                            Description = "Lovely",
                            Gender = "Female",
                            Name = "Betty"
                        });
                });

            modelBuilder.Entity("AnimalShelterAPI.Models.Dog", b =>
                {
                    b.Property<int>("DogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Gender")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("DogId");

                    b.ToTable("Dogs");

                    b.HasData(
                        new
                        {
                            DogId = 1,
                            Age = 4,
                            Description = "Lovely",
                            Gender = "Male",
                            Name = "Mike"
                        },
                        new
                        {
                            DogId = 2,
                            Age = 2,
                            Description = "Lovely",
                            Gender = "Male",
                            Name = "Dave"
                        },
                        new
                        {
                            DogId = 3,
                            Age = 5,
                            Description = "Lovely",
                            Gender = "Male",
                            Name = "Buster"
                        },
                        new
                        {
                            DogId = 4,
                            Age = 9,
                            Description = "Lovely",
                            Gender = "Female",
                            Name = "Penelope"
                        },
                        new
                        {
                            DogId = 5,
                            Age = 18,
                            Description = "Lovely",
                            Gender = "Female",
                            Name = "Emma"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
